### PR TITLE
Add Nostr Ruby Ideas to IDEAS.md

### PR DESCRIPTION
**Pull request by erskingardner**
Had a think about this yesterday and wanted to propose a few structural changes to make the gem more usable.

### CODE REVIEW

**Comment by dtonon** [comment]
Thanks Jeff, that makes total sense.
I will work on this format by integrating specific Kind types, with a proper validation, like proposed by https://github.com/dtonon/nostr-ruby/pull/3

**Comment by erskingardner** [comment]
I'm more than happy to contribute too. Just wanted to make sure that I didn't do a bunch of work before checking that you were behind the general direction.

I don't think it makes sense to nest modules too deeply and scope each module to a NIP (what #3 is doing). For devs, I believe it makes way more sense to use modules that match functionality they need to use. e.g. dealing with users, or events. If there are bits of code that get reused across many of those modules (nip-04 encryption) we can break those out into NIP focused modules to be included rather than nested. Thoughts?

**Comment by erskingardner** [comment]
LOL. I just found this nostr ruby library that looks like it's going in exactly the direction I was suggesting... https://github.com/wilsonsilva/nostr

Maybe we should both contribute there?

**Comment by dtonon** [comment]
> I don't think it makes sense to nest modules too deeply [..]

I also prefer to use modules, they add flexibility.
We can include specific NIPs module to implement conditional validations, or add/extend specific methods.

> LOL. I just found this nostr ruby library that looks like it's going in exactly the direction I was suggesting... https://github.com/wilsonsilva/nostr

Ah yes, I saw that months ago! At that time, they still didn't support NIP-04, but they had the relay part. It seems to be well organized!
I don't know, I hate to waste resources in equivalent parallel projects, but I'm fond of mine and I would like to improve it, even just to keep it for studying/training. What do you think?

**Comment by dtonon** [comment]
@erskingardner I'm going to close this issue because I just opened https://github.com/dtonon/nostr-ruby/pull/8 where we can discusso the new lib structure starting from my refactored code.

**Comment by dtonon** [comment]
@erskingardner I was reviewing again your ideas:

```
# Zap a user
user.zap(1337, "Zap comment")

# React to an event
event.react("🤙")

# Zap an event
event.zap(1337, "Zap comment")
```

This approach is problematic, because on the Event instance we don't have the private key to sign.

Whit the new structure I'm working on a reaction (we don't have the code to zap yet) is:

```

require_relative 'lib/nostr_ruby'
c = Nostr::Client.new("a727ffd7c6ffefa2a0b9f8a238885ea64caf6e0fe8f4daed590496f96999e341")
n = Nostr::ShortNote.new(
  "00bf316f2e2fc64dd4c502b281a2fdd945519164920720b788ece9746e5d3c65",
  "Hello world!"
)
c.sign(n)
r = Nostr::Reaction.new(
  "00bf316f2e2fc64dd4c502b281a2fdd945519164920720b788ece9746e5d3c65",
  n.id,
  n.pubkey,
  "🤟"
)
c.sign(r)
```

Probably we can compress it in a client action, like:

```
client.react(eventObj, "🤟")
```

**Comment by erskingardner** [comment]
One thing that NDK does really well is breaking the signer functionality into its own concept. That way you associate the signer you want (and you can change them out) to the client and then when you want to sign events, the event class looks for the associated signer to handle signing in whatever way that type of signer implements it. 

For example, if you had a bad signer class that had an unimplemented method called "sign", the sub classes that inherit from that parent class they would implement the sign method however they need.

**Comment by dtonon** [comment]
> That way you associate the signer you want to the client and then when you want to sign events, the event class looks for the associated signer 

Is the same thing I had in mind.
But how to associate the client (that is connected to the signer) and the event? I cannot understand this from your pseudo-code.

**Pull request closed without merging**
